### ISSUE TITLE
Allow observing norms / integrals over any field

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2034] opened 2020-02-27 19:13 UTC
# Feature request:

We should generalize `ObserveErrorNorms` to allow other norms than L2 and to work with any field, not just errors to the analytic solution. It should probably be renamed `ObserveNorms` then. We need to add compute items for the errors of fields to their analytic solution for this to work.

We also need to be able to take integrals over fields without taking a norm (L1 still takes an absolute value). This feature can be part of the generalized event or a separate event.

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment] 2020-02-27 19:21
This is essentially a duplicate of #1459

**Comment by nilsdeppe** [comment] 2022-06-05 01:04
Fixed in #3766

**Closed as completed by nilsdeppe** 2022-06-05 01:04 UTC
