### ISSUE TITLE
Random failure in Unit.Domain.CoordinateMaps.Wedge3D.Map

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#4397] opened 2022-11-19 19:42 UTC
# Bug reports:

```
:35:20.8263496Z Unit.Domain.CoordinateMaps.Wedge3D.Map
2022-10-31T22:35:20.8264067Z -------------------------------------------------------------------------------
2022-10-31T22:35:20.8264534Z /__w/spectre/spectre/tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp:357
2022-10-31T22:35:20.8264930Z ...............................................................................
2022-10-31T22:35:20.8265126Z 
2022-10-31T22:35:20.8265376Z /__w/spectre/spectre/tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.hpp:398: FAILED:
2022-10-31T22:35:20.8265796Z   REQUIRE( expected_test_point.has_value() )
2022-10-31T22:35:20.8266098Z with expansion:
2022-10-31T22:35:20.8266345Z   false
2022-10-31T22:35:20.8266574Z with messages:
2022-10-31T22:35:20.8266833Z   Wedge3d all directions
2022-10-31T22:35:20.8267185Z   Seed is: 97612616 from /__w/spectre/spectre/tests/Unit/Domain/CoordinateMaps/
2022-10-31T22:35:20.8267537Z   Test_Wedge3D.cpp:27
2022-10-31T22:35:20.8267817Z   inner_radius := 2.96152464874497889
2022-10-31T22:35:20.8268102Z   outer_radius := 6.62241454187172529
2022-10-31T22:35:20.8268399Z   inner_sphericity := 0.29081448153054645
2022-10-31T22:35:20.8268687Z   outer_sphericity := 0.93283272996157152
2022-10-31T22:35:20.8269200Z   half_opening_angle := 1.40807208699766062
2022-10-31T22:35:20.8269500Z   halves := 1
2022-10-31T22:35:20.8269760Z   orientation := (+0, +1, +2)
2022-10-31T22:35:20.8270053Z   with_equiangular_map := true
2022-10-31T22:35:20.8270334Z   radial_distribution := Linear
2022-10-31T22:35:20.8270694Z   Seed is: 1708564754 from /__w/spectre/spectre/tests/Unit/Helpers/Domain/
2022-10-31T22:35:20.8271076Z   CoordinateMaps/TestMapHelpers.hpp:428
2022-10-31T22:35:20.8271386Z   Test inverse map
2022-10-31T22:35:20.8271751Z   test_point := { 1.0, -1.0, -1.0 }
```
I'm not sure if this is just that the outer sphericity should be limited to something like 0.9.

**Comment by nilsdeppe** [comment] 2022-11-23 06:26
```
2022-11-23T02:34:51.4636695Z Unit.Domain.CoordinateMaps.Wedge3D.Map
2022-11-23T02:34:51.4637189Z -------------------------------------------------------------------------------
2022-11-23T02:34:51.4637614Z /__w/spectre/spectre/tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp:357
2022-11-23T02:34:51.4637978Z ...............................................................................
2022-11-23T02:34:51.4638262Z 
2022-11-23T02:34:51.4638490Z /__w/spectre/spectre/tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.hpp:398: FAILED:
2022-11-23T02:34:51.4638877Z   REQUIRE( expected_test_point.has_value() )
2022-11-23T02:34:51.4639158Z with expansion:
2022-11-23T02:34:51.4639380Z   false
2022-11-23T02:34:51.4639588Z with messages:
2022-11-23T02:34:51.4639824Z   Wedge3d all directions
2022-11-23T02:34:51.4640121Z   Seed is: 3559540305 from /__w/spectre/spectre/tests/Unit/Domain/
2022-11-23T02:34:51.4640447Z   CoordinateMaps/Test_Wedge3D.cpp:27
2022-11-23T02:34:51.4640922Z   inner_radius := 2.69047879065974271
2022-11-23T02:34:51.4641199Z   outer_radius := 5.40298785196271503
2022-11-23T02:34:51.4641485Z   inner_sphericity := 0.03977436312531508
2022-11-23T02:34:51.4641768Z   outer_sphericity := 0.80772737178585041
2022-11-23T02:34:51.4642073Z   half_opening_angle := 1.40985105662770427
2022-11-23T02:34:51.4642340Z   halves := 1
2022-11-23T02:34:51.4642592Z   orientation := (+0, +1, +2)
2022-11-23T02:34:51.4642871Z   with_equiangular_map := true
2022-11-23T02:34:51.4643150Z   radial_distribution := Linear
2022-11-23T02:34:51.4643499Z   Seed is: 1448445821 from /__w/spectre/spectre/tests/Unit/Helpers/Domain/
2022-11-23T02:34:51.4643874Z   CoordinateMaps/TestMapHelpers.hpp:428
2022-11-23T02:34:51.4644174Z   Test inverse map
2022-11-23T02:34:51.4644515Z   test_point := { 1.0, -1.0, -1.0 }
```

**Comment by wthrowe** [comment] 2022-12-21 21:29
Duplicate of #4133

**Closed as not planned by wthrowe** 2022-12-21 21:29 UTC
Labels: bug
