### ISSUE TITLE
Test failure: Unit.PointwiseFunctions.AnalyticData.ForceFree.RotatingDipole

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#5739] opened 2024-02-05 18:37 UTC
Failed randomly here: https://github.com/sxs-collaboration/spectre/actions/runs/7788773026/job/21238937382?pr=5737

@yoonso0-0 could you take this?

```
-------------------------------------------------------------------------------
Unit.PointwiseFunctions.AnalyticData.ForceFree.RotatingDipole
-------------------------------------------------------------------------------
../../../../../../tests/Unit/PointwiseFunctions/AnalyticData/ForceFree/Test_RotatingDipole.cpp:42
...............................................................................

../../../../../../tests/Unit/PointwiseFunctions/AnalyticData/ForceFree/Test_RotatingDipole.cpp:125: FAILED:
  CHECK( solution.interior_mask(random_coords) == mask_from_python )
with expansion:
  { } == T()=(1,1,1,1,1,1,1,1,1,1)
with message:
  Seed is: 1988790009 from ../../../../../../tests/Unit/PointwiseFunctions/
  AnalyticData/ForceFree/Test_RotatingDipole.cpp:118
```

**Comment by wthrowe** [comment] 2024-02-28 22:24
Duplicate of #5642.

**Closed as not planned by wthrowe** 2024-02-28 22:24 UTC
