### ISSUE TITLE
Random failure in Unit.Evolution.Systems.CurvedScalarWave.Characteristics

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#2330] opened 2020-06-19 18:32 UTC
# Bug reports:

### Expected behavior:

Test Unit.Evolution.Systems.CurvedScalarWave.Characteristics to pass

### Current behavior:
~~~
-------------------------------------------------------------------------------
922
Unit.Evolution.Systems.CurvedScalarWave.Characteristics
923
-------------------------------------------------------------------------------
924
/__w/spectre/spectre/tests/Unit/Evolution/Systems/CurvedScalarWave/Test_Characteristics.cpp:213
925
...............................................................................
926

927
/__w/spectre/spectre/tests/Unit/Framework/TestingFramework.hpp:166: FAILED:
928
  CHECK( a == appx(b) )
929
with expansion:
930
  -0.0019424794 == Approx( -0.0019424794 )
931
with messages:
932
  Seed is: 922975114 from /__w/spectre/spectre/tests/Unit/Framework/
933
  CheckWithRandomValues.hpp:359
934
  function: char_field_vzero
935
  /__w/spectre/spectre/tests/Unit/Framework/CheckWithRandomValues.hpp:233:
936
 /__w/spectre/spectre/tests/Unit/Framework/CheckWithRandomValues.hpp:233:
936
  result == pypp::call<ResultType>( module_name, function_name, std::get
937
  <ArgumentIs>(args)..., forward_to_pypp<ResultType>(std::get<MemberArgsIs>
938
  (member_args), used_for_size)...)
939
  a: T(0)=(3.354179417899831606e+02,-1.751156301793367618e+02,-2.
940
  755869325562594895e+03,-1.358067578051333612e+03,-8.948736674539960134e+00)
941
  T(1)=(2.706712817618916915e+02,-3.702738093567473925e+02,1.
942
  423425280101057297e+03,1.079648332774094797e+03,-1.357513746042992153e+01)
943
  T(2)=(-3.509305009705149132e+02,-3.977902435550667633e+03,8.
944
  167234460748465608e+03,-2.187599907446060570e+03,-1.942479399085428327e-03)
945
  b: T(0)=(3.354179417899827058e+02,-1.751156301793368186e+02,-2.
946
  755869325562594895e+03,-1.358067578051333612e+03,-8.948736674539802038e+00)
947
  T(1)=(2.706712817618914642e+02,-3.702738093567473925e+02,1.
948
  423425280101057297e+03,1.079648332774094797e+03,-1.357513746043008496e+01)
949
  T(2)=(-3.509305009705145153e+02,-3.977902435550668088e+03,8.
950
  167234460748464699e+03,-2.187599907446061479e+03,-1.942479400327101757e-03)
951
  a: (-3.509305009705149132e+02,-3.977902435550667633e+03,8.
952
  167234460748465608e+03,-2.187599907446060570e+03,-1.942479399085428327e-03)
953
  b: (-3.509305009705145153e+02,-3.977902435550668088e+03,8.
954
  167234460748464699e+03,-2.187599907446061479e+03,-1.942479400327101757e-03)
955
  a: -1.942479399085428327e-03
956
  b: -1.942479400327101757e-03
~~~

### Environment:

Test failure in GitHub actions:

https://github.com/sxs-collaboration/spectre/pull/2320/checks?check_run_id=788250839

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment] 2020-08-17 18:45
duplicate of #1981

**Closed as completed by kidder** 2020-08-17 18:45 UTC
