### ISSUE TITLE
Random failure in Unit.PointwiseFunctions.GeneralRelativity.GhQuantities

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#3014] opened 2021-03-20 18:28 UTC
# Bug reports:

### Expected behavior:

Test passes robustly

### Current behavior:

Please fix the test so that `ctest --repeat-until-fail 10000 -R TEST_NAME` succeeds.
It looks like some tensor components have large values; I suggest making sure input random values are of at most order unity

```
-------------------------------------------------------------------------------
Unit.PointwiseFunctions.GeneralRelativity.GhQuantities
-------------------------------------------------------------------------------
/__w/spectre/spectre/tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeGhQuantities.cpp:651
...............................................................................

/__w/spectre/spectre/tests/Unit/Framework/TestingFramework.hpp:147: FAILED:
  CHECK( a == appx(b) )
with expansion:
  4.99458125455210933
  ==
  Approx( 4.99458125454063406 )
with messages:
  Seed is: 3499063018 from /__w/spectre/spectre/tests/Unit/Framework/
  CheckWithRandomValues.hpp:333
  function: covariant_deriv_extrinsic_curvture
  /__w/spectre/spectre/tests/Unit/Framework/CheckWithRandomValues.hpp:221:
  result == pypp::call<ResultType>( module_name, function_name, std::get
  <ArgumentIs>(args)..., forward_to_pypp<ResultType>(std::get<MemberArgsIs>
  (member_args), used_for_size)...)
  a := T(0,0,0)=(4043.43,-659.099,7377.56,16510,-1091.19)
  T(1,0,0)=(996.9,-6191.22,-15457.3,44752.5,7007.65)
  T(2,0,0)=(6357.57,22649.4,59837.4,100220,18568.7)
  T(0,1,0)=(-260.095,10858.4,-7849.66,-10007.6,-3764.53)
  T(1,1,0)=(2037.69,7406.66,11558.6,-670.059,3927.79)
  T(2,1,0)=(6591.52,-22621.2,-85011.2,-31075,-3586.62)
  T(0,2,0)=(6524.49,7490.35,9509.79,4022.81,-1732.06)
  T(1,2,0)=(1243.85,8397.18,16903.8,1350.57,-115.355)
  T(2,2,0)=(6841.44,-23630.5,-151795,10462.2,-5183.86)
  T(0,1,1)=(4042.43,1484.16,6211.33,8342.86,-6790.94)
  T(1,1,1)=(-2105.75,2813.77,-17001.2,33372.5,16966.3)
  T(2,1,1)=(-4585.23,-13504.2,63818.3,72147.4,18654)
  T(0,2,1)=(1213.5,-36098.9,4.99458,-25980,-841.92)
  T(1,2,1)=(-2127.04,-22204.2,6693.91,-44676.5,3949.69)
  T(2,2,1)=(-4731.41,57779.6,-99784,-139664,11079.4)
  T(0,2,2)=(-18290,54243.1,1731.19,-23272.2,-2533.31)
  T(1,2,2)=(-1469.43,38412.2,-505.77,-53253.9,11161)
  T(2,2,2)=(-12058.6,-106427,66123.2,-147604,18294.5)
  b := T(0,0,0)=(4043.43,-659.099,7377.56,16510,-1091.19)
  T(1,0,0)=(996.9,-6191.22,-15457.3,44752.5,7007.65)
  T(2,0,0)=(6357.57,22649.4,59837.4,100220,18568.7)
  T(0,1,0)=(-260.095,10858.4,-7849.66,-10007.6,-3764.53)
  T(1,1,0)=(2037.69,7406.66,11558.6,-670.059,3927.79)
  T(2,1,0)=(6591.52,-22621.2,-85011.2,-31075,-3586.62)
  T(0,2,0)=(6524.49,7490.35,9509.79,4022.81,-1732.06)
  T(1,2,0)=(1243.85,8397.18,16903.8,1350.57,-115.355)
  T(2,2,0)=(6841.44,-23630.5,-151795,10462.2,-5183.86)
  T(0,1,1)=(4042.43,1484.16,6211.33,8342.86,-6790.94)
  T(1,1,1)=(-2105.75,2813.77,-17001.2,33372.5,16966.3)
  T(2,1,1)=(-4585.23,-13504.2,63818.3,72147.4,18654)
  T(0,2,1)=(1213.5,-36098.9,4.99458,-25980,-841.92)
  T(1,2,1)=(-2127.04,-22204.2,6693.91,-44676.5,3949.69)
  T(2,2,1)=(-4731.41,57779.6,-99784,-139664,11079.4)
  T(0,2,2)=(-18290,54243.1,1731.19,-23272.2,-2533.31)
  T(1,2,2)=(-1469.43,38412.2,-505.77,-53253.9,11161)
  T(2,2,2)=(-12058.6,-106427,66123.2,-147604,18294.5)
  a := (1213.5,-36098.9,4.99458,-25980,-841.92)
  b := (1213.5,-36098.9,4.99458,-25980,-841.92)
```

### Environment:
From CI
https://github.com/sxs-collaboration/spectre/pull/3010/checks?check_run_id=2152899864

**Comment by nilsdeppe** [comment] 2021-03-21 03:57
Duplicate of #3011

**Closed as completed by nilsdeppe** 2021-03-21 03:57 UTC
Labels: bug, duplicate
